server:
  port: 8010 # 用户服务占用 8010 端口

spring:
  application:
    name: seckill-user # 【重要】服务名，以后别人找你就靠这个名字

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos 地址 (Linux IP)

  # 数据库配置 (沿用之前的)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Hzj760322

# MyBatis-Plus 配置 (可选，但推荐加上以打印 SQL 日志)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台 SQL 日志，方便调试
  global-config:
    db-config:
      logic-delete-field: deleted # 如果你有逻辑删除需求